name: Build & Push Frontend

on:
    push:
        branches: ['main']
        paths: ['.github/workflows/build-frontend.yaml', 'deploy/docker-compose.yaml', 'app/**']
    workflow_dispatch:

env:
    FRONTEND_IMAGE: ghcr.io/dikobrazik/squad-speak-frontend

jobs:
    build-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # по сути любой может увидеть секреты, залитые в образ
            - name: 'Create env file'
              run: |
                  echo "${{ secrets.ENV_FRONTEND }}" > ./app/.env

            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Frontend
              uses: docker/build-push-action@v5
              with:
                  # Нужно, чтобы action не подтягивал репозиторий заново
                  context: .
                  file: ./app/deploy/Dockerfile
                  push: true
                  tags: ${{ env.FRONTEND_IMAGE }}
